import { QuizQuestion } from './quiz';

export const DEFAULT_QUESTIONS: QuizQuestion[] = [
  { id: 'q_sci_01', category: 'Science', text: 'Quel est le symbole chimique de l\'or ?', answers: ['Au', 'Ag', 'Fe', 'Or'], correctIndex: 0, difficulty: 1 },
  { id: 'q_sci_02', category: 'Science', text: 'Combien de planètes compte notre système solaire ?', answers: ['8', '9', '7', '10'], correctIndex: 0, difficulty: 1 },
  { id: 'q_sci_03', category: 'Science', text: 'Quelle est la vitesse de la lumière (environ) ?', answers: ['300 000 km/s', '150 000 km/s', '1 000 000 km/s', '100 000 km/s'], correctIndex: 0, difficulty: 1 },
  { id: 'q_sci_04', category: 'Science', text: 'Quel gaz les plantes absorbent-elles pour la photosynthèse ?', answers: ['CO2', 'O2', 'N2', 'H2'], correctIndex: 0, difficulty: 1 },
  { id: 'q_sci_05', category: 'Science', text: 'Quelle est l\'unité de la force ?', answers: ['Newton', 'Joule', 'Watt', 'Pascal'], correctIndex: 0, difficulty: 2 },
  { id: 'q_sci_06', category: 'Science', text: 'Quel est l\'élément le plus abondant dans l\'univers ?', answers: ['Hydrogène', 'Hélium', 'Oxygène', 'Carbone'], correctIndex: 0, difficulty: 2 },
  { id: 'q_sci_07', category: 'Science', text: 'Qui a formulé la théorie de la relativité ?', answers: ['Einstein', 'Newton', 'Bohr', 'Planck'], correctIndex: 0, difficulty: 1 },
  { id: 'q_sci_08', category: 'Science', text: 'Quel est le point d\'ébullition de l\'eau au niveau de la mer ?', answers: ['100°C', '90°C', '110°C', '120°C'], correctIndex: 0, difficulty: 1 },
  { id: 'q_sci_09', category: 'Science', text: 'Combien de chromosomes possède un humain ?', answers: ['46', '48', '44', '42'], correctIndex: 0, difficulty: 2 },
  { id: 'q_sci_10', category: 'Science', text: 'Quelle planète est surnommée la planète rouge ?', answers: ['Mars', 'Vénus', 'Jupiter', 'Mercure'], correctIndex: 0, difficulty: 1 },

  { id: 'q_his_01', category: 'Histoire', text: 'En quelle année a eu lieu la Révolution française ?', answers: ['1789', '1776', '1815', '1848'], correctIndex: 0, difficulty: 1 },
  { id: 'q_his_02', category: 'Histoire', text: 'Qui était le premier empereur de France ?', answers: ['Napoléon Ier', 'Charlemagne', 'Louis XIV', 'César'], correctIndex: 0, difficulty: 1 },
  { id: 'q_his_03', category: 'Histoire', text: 'En quelle année a commencé la Première Guerre mondiale ?', answers: ['1914', '1918', '1939', '1905'], correctIndex: 0, difficulty: 1 },
  { id: 'q_his_04', category: 'Histoire', text: 'Quel mur est tombé en 1989 ?', answers: ['Le mur de Berlin', 'Le mur d\'Hadrien', 'Le mur des Lamentations', 'La grande muraille'], correctIndex: 0, difficulty: 1 },
  { id: 'q_his_05', category: 'Histoire', text: 'Qui a découvert l\'Amérique en 1492 ?', answers: ['Christophe Colomb', 'Magellan', 'Marco Polo', 'Vasco de Gama'], correctIndex: 0, difficulty: 1 },
  { id: 'q_his_06', category: 'Histoire', text: 'Quelle civilisation a bâti les pyramides de Gizeh ?', answers: ['Égyptienne', 'Maya', 'Romaine', 'Grecque'], correctIndex: 0, difficulty: 1 },
  { id: 'q_his_07', category: 'Histoire', text: 'En quelle année l\'Homme a-t-il marché sur la Lune ?', answers: ['1969', '1965', '1972', '1959'], correctIndex: 0, difficulty: 1 },
  { id: 'q_his_08', category: 'Histoire', text: 'Qui était le chef des Gaulois à Alésia ?', answers: ['Vercingétorix', 'Attila', 'Brennus', 'Ambiorix'], correctIndex: 0, difficulty: 2 },
  { id: 'q_his_09', category: 'Histoire', text: 'Quel traité a mis fin à la Seconde Guerre mondiale en Europe ?', answers: ['Capitulation de 1945', 'Traité de Versailles', 'Traité de Rome', 'Accords d\'Évian'], correctIndex: 0, difficulty: 2 },
  { id: 'q_his_10', category: 'Histoire', text: 'Quelle dynastie régnait sur la France en 1600 ?', answers: ['Bourbon', 'Valois', 'Capétien', 'Mérovingien'], correctIndex: 0, difficulty: 3 },

  { id: 'q_geo_01', category: 'Géographie', text: 'Quelle est la capitale de la France ?', answers: ['Paris', 'Lyon', 'Marseille', 'Nice'], correctIndex: 0, difficulty: 1 },
  { id: 'q_geo_02', category: 'Géographie', text: 'Quel est le plus grand océan du monde ?', answers: ['Pacifique', 'Atlantique', 'Indien', 'Arctique'], correctIndex: 0, difficulty: 1 },
  { id: 'q_geo_03', category: 'Géographie', text: 'Quel est le plus haut sommet du monde ?', answers: ['Everest', 'K2', 'Mont Blanc', 'Kilimandjaro'], correctIndex: 0, difficulty: 1 },
  { id: 'q_geo_04', category: 'Géographie', text: 'Quel désert est le plus grand désert chaud ?', answers: ['Sahara', 'Gobi', 'Kalahari', 'Atacama'], correctIndex: 0, difficulty: 1 },
  { id: 'q_geo_05', category: 'Géographie', text: 'Combien de pays composent l\'Union européenne ?', answers: ['27', '25', '28', '30'], correctIndex: 0, difficulty: 2 },
  { id: 'q_geo_06', category: 'Géographie', text: 'Quel fleuve traverse le Caire ?', answers: ['Le Nil', 'Le Tigre', 'L\'Euphrate', 'Le Jourdain'], correctIndex: 0, difficulty: 2 },
  { id: 'q_geo_07', category: 'Géographie', text: 'Quelle est la plus grande île du monde ?', answers: ['Groenland', 'Madagascar', 'Bornéo', 'Australie'], correctIndex: 0, difficulty: 2 },
  { id: 'q_geo_08', category: 'Géographie', text: 'Quel pays a la plus grande population ?', answers: ['Inde', 'Chine', 'États-Unis', 'Indonésie'], correctIndex: 0, difficulty: 2 },
  { id: 'q_geo_09', category: 'Géographie', text: 'Quelle est la capitale de l\'Australie ?', answers: ['Canberra', 'Sydney', 'Melbourne', 'Perth'], correctIndex: 0, difficulty: 2 },
  { id: 'q_geo_10', category: 'Géographie', text: 'Quel détroit sépare l\'Europe de l\'Afrique ?', answers: ['Gibraltar', 'Bosphore', 'Malacca', 'Béring'], correctIndex: 0, difficulty: 2 },

  { id: 'q_spt_01', category: 'Sport', text: 'Combien de joueurs compte une équipe de football ?', answers: ['11', '10', '12', '9'], correctIndex: 0, difficulty: 1 },
  { id: 'q_spt_02', category: 'Sport', text: 'Quel sport se joue à Wimbledon ?', answers: ['Tennis', 'Golf', 'Cricket', 'Polo'], correctIndex: 0, difficulty: 1 },
  { id: 'q_spt_03', category: 'Sport', text: 'Combien de points vaut un panier à 3 points au basketball ?', answers: ['3', '2', '1', '4'], correctIndex: 0, difficulty: 1 },
  { id: 'q_spt_04', category: 'Sport', text: 'Quel pays a gagné la Coupe du monde 2018 ?', answers: ['France', 'Brésil', 'Allemagne', 'Argentine'], correctIndex: 0, difficulty: 1 },
  { id: 'q_spt_05', category: 'Sport', text: 'En boxe, comment s\'appelle le ring ?', answers: ['Le ring', 'Le tapis', 'La piste', 'La scène'], correctIndex: 0, difficulty: 1 },
  { id: 'q_spt_06', category: 'Sport', text: 'Quel nageur a gagné 23 médailles d\'or olympiques ?', answers: ['Phelps', 'Spitz', 'Thorpe', 'Bolt'], correctIndex: 0, difficulty: 2 },
  { id: 'q_spt_07', category: 'Sport', text: 'Combien de sets pour gagner au tennis masculin en Grand Chelem ?', answers: ['3', '2', '4', '5'], correctIndex: 3, difficulty: 2 },
  { id: 'q_spt_08', category: 'Sport', text: 'Quel sport est surnommé le « sport roi » ?', answers: ['Football', 'Tennis', 'Basket', 'Rugby'], correctIndex: 0, difficulty: 1 },
  { id: 'q_spt_09', category: 'Sport', text: 'Quelle équipe a le plus de titres de champion d\'Europe de football ?', answers: ['Real Madrid', 'Milan', 'Barcelone', 'Liverpool'], correctIndex: 0, difficulty: 3 },
  { id: 'q_spt_10', category: 'Sport', text: 'Au rugby, combien de points vaut un essai ?', answers: ['5', '3', '7', '2'], correctIndex: 0, difficulty: 2 },

  { id: 'q_cul_01', category: 'Culture', text: 'Qui a peint la Joconde ?', answers: ['De Vinci', 'Picasso', 'Van Gogh', 'Rembrandt'], correctIndex: 0, difficulty: 1 },
  { id: 'q_cul_02', category: 'Culture', text: 'Quel écrivain a écrit « Les Misérables » ?', answers: ['Victor Hugo', 'Balzac', 'Zola', 'Flaubert'], correctIndex: 0, difficulty: 1 },
  { id: 'q_cul_03', category: 'Culture', text: 'Combien de cordes possède un violon ?', answers: ['4', '5', '6', '3'], correctIndex: 0, difficulty: 1 },
  { id: 'q_cul_04', category: 'Culture', text: 'Qui a composé la Neuvième Symphonie ?', answers: ['Beethoven', 'Mozart', 'Bach', 'Chopin'], correctIndex: 0, difficulty: 2 },
  { id: 'q_cul_05', category: 'Culture', text: 'Quel est le pays du festival de Cannes ?', answers: ['France', 'Italie', 'Espagne', 'Suisse'], correctIndex: 0, difficulty: 1 },
  { id: 'q_cul_06', category: 'Culture', text: 'Quelle œuvre est au Louvre ?', answers: ['La Vénus de Milo', 'Le Penseur', 'La Liberté guidant le peuple', 'Les Nymphéas'], correctIndex: 0, difficulty: 2 },
  { id: 'q_cul_07', category: 'Culture', text: 'Qui a écrit « Harry Potter » ?', answers: ['J.K. Rowling', 'Stephen King', 'J.R.R. Tolkien', 'Dan Brown'], correctIndex: 0, difficulty: 1 },
  { id: 'q_cul_08', category: 'Culture', text: 'Quel peintre a coupé l\'oreille de... Van Gogh ?', answers: ['Van Gogh', 'Gauguin', 'Cézanne', 'Monet'], correctIndex: 0, difficulty: 2 },
  { id: 'q_cul_09', category: 'Culture', text: 'Quelle langue possède le plus de locuteurs natifs ?', answers: ['Mandarin', 'Anglais', 'Espagnol', 'Hindi'], correctIndex: 0, difficulty: 3 },
  { id: 'q_cul_10', category: 'Culture', text: 'Combien de symphonies a écrit Beethoven ?', answers: ['9', '7', '8', '10'], correctIndex: 0, difficulty: 2 },

  { id: 'q_jv_01', category: 'Jeux vidéo', text: 'Quel est le plombier le plus célèbre ?', answers: ['Mario', 'Luigi', 'Sonic', 'Crash'], correctIndex: 0, difficulty: 1 },
  { id: 'q_jv_02', category: 'Jeux vidéo', text: 'Quel jeu a inventé le battle royale ?', answers: ['PUBG', 'Fortnite', 'Apex', 'H1Z1'], correctIndex: 0, difficulty: 3 },
  { id: 'q_jv_03', category: 'Jeux vidéo', text: 'Quelle console a été lancée par Sony en 2020 ?', answers: ['PS5', 'PS4', 'PS4 Pro', 'PS Vita'], correctIndex: 0, difficulty: 1 },
  { id: 'q_jv_04', category: 'Jeux vidéo', text: 'Quel personnage porte une casquette rouge ?', answers: ['Mario', 'Link', 'Kratos', 'Master Chief'], correctIndex: 0, difficulty: 1 },
  { id: 'q_jv_05', category: 'Jeux vidéo', text: 'Quel jeu suit Steve dans le monde de Minecraft ?', answers: ['Minecraft', 'Terraria', 'Roblox', 'Lego Worlds'], correctIndex: 0, difficulty: 1 },
  { id: 'q_jv_06', category: 'Jeux vidéo', text: 'Quelle franchise met en scène une princesse Zelda ?', answers: ['Zelda', 'Mario', 'Kirby', 'Metroid'], correctIndex: 0, difficulty: 1 },
  { id: 'q_jv_07', category: 'Jeux vidéo', text: 'Quel jeu a été créé par Markus Persson (Notch) ?', answers: ['Minecraft', 'Terraria', 'Factorio', 'Stardew Valley'], correctIndex: 0, difficulty: 2 },
  { id: 'q_jv_08', category: 'Jeux vidéo', text: 'Quel est le nom du héros de « The Legend of Zelda » ?', answers: ['Link', 'Zelda', 'Ganon', 'Epona'], correctIndex: 0, difficulty: 1 },
  { id: 'q_jv_09', category: 'Jeux vidéo', text: 'Quelle série a un protagoniste nommé Lara Croft ?', answers: ['Tomb Raider', 'Uncharted', 'Assassin\'s Creed', 'Far Cry'], correctIndex: 0, difficulty: 1 },
  { id: 'q_jv_10', category: 'Jeux vidéo', text: 'Quel studio a créé Pokémon ?', answers: ['Game Freak', 'Nintendo', 'Sega', 'Square Enix'], correctIndex: 0, difficulty: 2 },
];
